export enum NotificationType {
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  PLAYLIST_SHARED = 'PLAYLIST_SHARED',
  COLLABORATOR_ADDED = 'COLLABORATOR_ADDED',
  TRACK_ADDED_TO_PLAYLIST = 'TRACK_ADDED_TO_PLAYLIST',
  NEW_RELEASE = 'NEW_RELEASE',
  TRANSCODE_FAILED = 'TRANSCODE_FAILED',
  SYSTEM = 'SYSTEM',
}
