{{- if .Values.monitoring.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "music-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "music-app.labels" . | nindent 8 }}
        app.kubernetes.io/name: kibana
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.monitoring.kibana.image.repository }}:{{ .Values.monitoring.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: '["http://elasticsearch:9200"]'
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          resources:
            {{- toYaml .Values.monitoring.kibana.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "music-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
{{- end }}
