from __future__ import annotations
from typing import Optional, Protocol, runtime_checkable

from music_events.models import TrackPlayedData, TrackPublishedData, UserFollowedData

from .entities import FeedbackAction, TasteProfile, TrackRec


@runtime_checkable
class IGraphRepository(Protocol):
    async def get_collaborative_recs(self, user_id: str, limit: int) -> list[TrackRec]: ...
    async def get_popular_tracks(self, limit: int) -> list[TrackRec]: ...
    async def get_discover_weekly(self, user_id: str, limit: int) -> list[TrackRec]: ...
    async def get_similar_tracks(self, track_id: str, limit: int) -> list[TrackRec]: ...
    async def get_radio_tracks(self, track_id: str, limit: int) -> list[TrackRec]: ...
    async def get_taste_profile(self, user_id: str) -> TasteProfile: ...
    async def count_user_listens(self, user_id: str) -> int: ...
    async def record_feedback(self, user_id: str, track_id: str, action: FeedbackAction) -> None: ...
    async def merge_track_played(self, data: TrackPlayedData) -> None: ...
    async def merge_track_published(self, data: TrackPublishedData) -> None: ...
    async def merge_user_followed(self, data: UserFollowedData) -> None: ...


@runtime_checkable
class ICacheService(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: str, ttl: int) -> None: ...
    async def delete(self, *keys: str) -> None: ...
